In [1]:
import json
import pandas as pd

# Part 1: Reading and investigating data

Open up the `player_data.json` and investigate the data structure.

In [335]:
#your code here
# df = pd.read_json('player_data.json')
# df
with open('player_data.json') as file:
    data = json.load(file)
data[0].keys()

dict_keys(['PERSON_ID', 'FIRST_NAME', 'LAST_NAME', 'DISPLAY_FIRST_LAST', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FI_LAST', 'BIRTHDATE', 'SCHOOL', 'COUNTRY', 'LAST_AFFILIATION', 'HEIGHT', 'WEIGHT', 'SEASON_EXP', 'JERSEY', 'POSITION', 'ROSTERSTATUS', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CODE', 'TEAM_CITY', 'PLAYERCODE', 'FROM_YEAR', 'TO_YEAR', 'DLEAGUE_FLAG', 'NBA_FLAG', 'GAMES_PLAYED_FLAG', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'CAREER_STATS', 'GAMELOG'])

# Part 2:  Creating the Dataframe

Create a data frame where each row corresponds to a game for each player. You must have atleast the following columns in your final dataframe:

'DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID', 'AST', 'BLK', 'DREB','Game_ID',  'MIN', 'PTS', 'REB', 'TEAM_ABBREVIATION'

*You can include additional columns in your dataframe, so you don't have to do additional work to remove other columns.*

In [19]:
df = pd.DataFrame()

for person in data:
    if len(person['GAMELOG']) == 0:
        continue
    df1 = pd.DataFrame(person, columns=['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID'], index=[0])
    df2 = pd.DataFrame(person['GAMELOG'])
    merged = pd.merge(df1, df2, left_on='PERSON_ID', right_on='Player_ID', how='outer')
    df = pd.concat([df, merged])
    
df.reset_index(drop=True, inplace=True)
df

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
0,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
1,Alex Abrines,203518,0,0,0,1,2,1,0.500,2,...,3,203518,1,22018,0,OKC,1610612760,0,1,W
2,Alex Abrines,203518,0,0,2,1,5,1,0.200,6,...,7,203518,1,22018,0,OKC,1610612760,0,1,L
3,Alex Abrines,203518,0,0,0,1,4,2,0.500,4,...,6,203518,1,22018,0,OKC,1610612760,0,1,W
4,Alex Abrines,203518,0,1,0,1,7,3,0.429,7,...,9,203518,1,22018,0,OKC,1610612760,0,1,W
5,Alex Abrines,203518,0,0,0,1,3,2,0.667,4,...,8,203518,3,22018,1,OKC,1610612760,0,1,W
6,Alex Abrines,203518,0,0,0,4,2,0,0.000,4,...,6,203518,4,22018,0,OKC,1610612760,0,1,W
7,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,1,1,L
8,Alex Abrines,203518,0,2,0,1,5,1,0.200,6,...,5,203518,1,22018,1,OKC,1610612760,0,1,L
9,Alex Abrines,203518,0,0,0,3,1,0,0.000,2,...,0,203518,3,22018,1,OKC,1610612760,2,1,W
10,Alex Abrines,203518,0,1,0,3,4,1,0.250,4,...,3,203518,3,22018,0,OKC,1610612760,1,1,L
11,Alex Abrines,203518,0,1,0,1,2,0,0.000,2,...,0,203518,1,22018,3,OKC,1610612760,1,1,W
12,Alex Abrines,203518,0,1,0,1,2,0,0.000,3,...,2,203518,1,22018,0,OKC,1610612760,1,1,W
13,Alex Abrines,203518,0,1,0,2,11,7,0.636,11,...,21,203518,2,22018,0,OKC,1610612760,0,1,W
14,Alex Abrines,203518,0,1,0,2,8,1,0.125,9,...,3,203518,3,22018,0,OKC,1610612760,0,1,W
15,Alex Abrines,203518,0,1,0,1,2,0,0.000,2,...,0,203518,1,22018,0,OKC,1610612760,0,1,L
16,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
17,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,1,1,W
18,Alex Abrines,203518,0,2,1,2,6,2,0.333,6,...,8,203518,2,22018,2,OKC,1610612760,1,1,W
19,Alex Abrines,203518,0,0,0,2,4,2,0.500,6,...,6,203518,2,22018,0,OKC,1610612760,1,1,L
20,Alex Abrines,203518,0,0,0,3,3,0,0.000,3,...,0,203518,4,22018,1,OKC,1610612760,1,1,W
21,Alex Abrines,203518,0,0,0,0,10,3,0.300,12,...,9,203518,0,22018,1,OKC,1610612760,0,1,W
22,Alex Abrines,203518,0,3,0,4,2,1,0.500,4,...,7,203518,4,22018,0,OKC,1610612760,1,1,W
23,Alex Abrines,203518,0,2,2,1,7,2,0.286,8,...,8,203518,1,22018,0,OKC,1610612760,0,1,W
24,Alex Abrines,203518,0,0,0,2,10,5,0.500,15,...,25,203518,2,22018,0,OKC,1610612760,0,1,W
25,Alex Abrines,203518,0,0,1,0,1,1,1.000,2,...,3,203518,0,22018,4,OKC,1610612760,1,1,W
26,Alex Abrines,203518,0,0,0,1,3,0,0.000,5,...,2,203518,1,22018,2,OKC,1610612760,0,1,W
27,Alex Abrines,203518,0,1,0,1,5,2,0.400,5,...,6,203518,1,22018,0,OKC,1610612760,0,1,L
28,Alex Abrines,203518,0,2,0,1,1,0,0.000,1,...,0,203518,1,22018,0,OKC,1610612760,0,1,L
29,Alex Abrines,203518,0,1,0,1,7,2,0.286,10,...,10,203518,2,22018,1,OKC,1610612760,2,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26071,Ivica Zubac,1627826,1610612746,3,0,0,0,0,0.000,5,...,7,1627826,2,22018,0,LAL,1610612747,2,1,L
26072,Ivica Zubac,1627826,1610612746,0,4,11,0,0,0.000,16,...,24,1627826,16,22018,0,LAL,1610612747,2,1,W
26073,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.000,12,...,10,1627826,8,22018,0,LAL,1610612747,4,1,L
26074,Ivica Zubac,1627826,1610612746,0,1,4,0,0,0.000,8,...,18,1627826,4,22018,0,LAL,1610612747,2,1,L
26075,Ivica Zubac,1627826,1610612746,1,1,5,0,0,0.000,6,...,17,1627826,7,22018,0,LAL,1610612747,0,1,L
26076,Ivica Zubac,1627826,1610612746,1,0,6,0,0,0.000,14,...,26,1627826,12,22018,0,LAL,1610612747,4,1,W
26077,Ivica Zubac,1627826,1610612746,1,0,3,0,0,0.000,2,...,7,1627826,3,22018,0,LAL,1610612747,0,1,W
26078,Ivica Zubac,1627826,1610612746,0,2,2,0,0,0.000,3,...,5,1627826,2,22018,0,LAL,1610612747,0,1,L
26079,Ivica Zubac,1627826,1610612746,1,1,3,0,0,0.000,10,...,10,1627826,5,22018,0,LAL,1610612747,0,1,L
26080,Ivica Zubac,1627826,1610612746,1,0,6,0,0,0.000,8,...,11,1627826,9,22018,1,LAL,1610612747,0,1,W
26081,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,2,...,4,1627826,2,22018,0,LAL,1610612747,1,1,W
26082,Ivica Zubac,1627826,1610612746,0,0,6,0,0,0.000,6,...,9,1627826,8,22018,0,LAL,1610612747,2,1,L
26083,Ivica Zubac,1627826,1610612746,2,1,4,0,0,0.000,6,...,10,1627826,6,22018,0,LAL,1610612747,1,1,L
26084,Ivica Zubac,1627826,1610612746,1,1,1,0,0,0.000,4,...,8,1627826,2,22018,0,LAL,1610612747,1,1,L
26085,Ivica Zubac,1627826,1610612746,3,1,0,0,0,0.000,8,...,7,1627826,2,22018,0,LAL,1610612747,2,1,L
26086,Ivica Zubac,1627826,1610612746,0,1,3,0,0,0.000,8,...,6,1627826,5,22018,0,LAL,1610612747,1,1,L
26087,Ivica Zubac,1627826,1610612746,2,2,8,0,0,0.000,10,...,18,1627826,11,22018,0,LAL,1610612747,1,1,W
26088,Ivica Zubac,1627826,1610612746,1,4,3,0,0,0.000,12,...,19,1627826,4,22018,0,LAL,1610612747,1,1,L
26089,Ivica Zubac,1627826,1610612746,0,2,9,0,0,0.000,10,...,16,1627826,11,22018,2,LAL,1610612747,1,1,W
26090,Ivica Zubac,1627826,1610612746,1,1,0,0,0,0.000,1,...,0,1627826,0,22018,0,LAL,1610612747,0,1,L
26091,Ivica Zubac,1627826,1610612746,1,0,2,0,0,0.000,2,...,4,1627826,2,22018,0,LAL,1610612747,0,1,L
26092,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,4,...,6,1627826,1,22018,0,LAL,1610612747,0,1,W
26093,Ivica Zubac,1627826,1610612746,0,1,2,0,0,0.000,0,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26094,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,0,...,0,1627826,1,22018,0,LAL,1610612747,0,1,W
26095,Ivica Zubac,1627826,1610612746,0,1,1,0,0,0.000,2,...,0,1627826,2,22018,0,LAL,1610612747,1,1,L
26096,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,2,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26097,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.000,3,...,5,1627826,6,22018,0,LAL,1610612747,1,1,L
26098,Ivica Zubac,1627826,1610612746,0,0,4,0,0,0.000,5,...,9,1627826,8,22018,1,LAL,1610612747,2,1,W
26099,Ivica Zubac,1627826,1610612746,1,0,1,0,0,0.000,1,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26100,Ivica Zubac,1627826,1610612746,0,1,0,0,0,0.000,1,...,0,1627826,1,22018,0,LAL,1610612747,0,1,L

In [47]:
df.head()
df.columns

Index(['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID_x', 'AST', 'BLK', 'DREB',
       'FG3A', 'FG3M', 'FG3_PCT', 'FGA', 'FGM', 'FG_PCT', 'FTA', 'FTM',
       'FT_PCT', 'GAME_DATE', 'Game_ID', 'MATCHUP', 'MIN', 'OREB', 'PF',
       'PLUS_MINUS', 'PTS', 'Player_ID', 'REB', 'SEASON_ID', 'STL',
       'TEAM_ABBREVIATION', 'TEAM_ID_y', 'TOV', 'VIDEO_AVAILABLE', 'WL'],
      dtype='object')

# Part 3: Pandas Questions

Answer the following questions

## 1 
- Find the player who scored the most points in an individual game last season.

-  Now do the same for rebounds, blocks, and assists.

In [36]:
# Your code here
#df[['DISPLAY_FIRST_LAST', 'PTS']].max()
print('PTS: ' + df.loc[df['PTS'].idxmax()]['DISPLAY_FIRST_LAST'])
print('REB: ' + df.loc[df['REB'].idxmax()]['DISPLAY_FIRST_LAST'])
print('BLK: ' + df.loc[df['BLK'].idxmax()]['DISPLAY_FIRST_LAST'])
print('AST: ' + df.loc[df['AST'].idxmax()]['DISPLAY_FIRST_LAST'])

PTS: James Harden
REB: Karl-Anthony Towns
BLK: Mitchell Robinson
AST: Russell Westbrook

## 2: 

- Find the player who scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [199]:
#your code here
print('PTS: ' + df.groupby(['DISPLAY_FIRST_LAST']).PTS.sum().sort_values(ascending=False).index[0])
print('REB: ' + df.groupby(['DISPLAY_FIRST_LAST']).REB.sum().sort_values(ascending=False).index[0])
print('BLK: ' + df.groupby(['DISPLAY_FIRST_LAST']).BLK.sum().sort_values(ascending=False).index[0])
print('AST: ' + df.groupby(['DISPLAY_FIRST_LAST']).AST.sum().sort_values(ascending=False).index[0])

PTS: James Harden
REB: Andre Drummond
BLK: Myles Turner
AST: Russell Westbrook

## 3:
How many players played in at least 82 games last season?

In [63]:
#your code here
sum(df.groupby(['DISPLAY_FIRST_LAST']).PERSON_ID.value_counts()>=82)

21

## 4: 
- Find which team scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [68]:
# your code here
print('PTS: '+df.groupby(['TEAM_ABBREVIATION']).PTS.sum().sort_values(ascending=False).index[0])
print('REB: '+df.groupby(['TEAM_ABBREVIATION']).REB.sum().sort_values(ascending=False).index[0])
print('BLK: '+df.groupby(['TEAM_ABBREVIATION']).BLK.sum().sort_values(ascending=False).index[0])
print('AST: '+df.groupby(['TEAM_ABBREVIATION']).AST.sum().sort_values(ascending=False).index[0])

PTS: MIL
REB: MIL
BLK: GSW
AST: GSW

## 5:
Which team had the most players play for them last season?

In [338]:
#your code here
df1 = df.groupby('TEAM_ABBREVIATION').DISPLAY_FIRST_LAST.value_counts()
df2 = df1.reset_index(name='count').TEAM_ABBREVIATION.value_counts().index[1]

df2

'MEM'

## 6:
- Did any players play for more than one team last year?

- What is the most number of teams a player played for last season?

In [219]:
df.groupby(['DISPLAY_FIRST_LAST']).TEAM_ABBREVIATION.value_counts().reset_index(name='count').DISPLAY_FIRST_LAST.value_counts()

Alec Burks           3
Wesley Matthews      3
Greg Monroe          3
Isaiah Canaan        3
Andrew Harrison      3
Jason Smith          3
Garrett Temple       2
Tobias Harris        2
Tyler Johnson        2
Marc Gasol           2
Mike Muscala         2
Mike Scott           2
Enes Kanter          2
Kelly Oubre Jr.      2
Rodney Hood          2
Ivica Zubac          2
Wayne Selden         2
Skal Labissiere      2
Marquese Chriss      2
Jeremy Lin           2
Jimmy Butler         2
Reggie Bullock       2
Austin Rivers        2
Corey Brewer         2
Tim Frazier          2
Delon Wright         2
Avery Bradley        2
Jawun Evans          2
Thon Maker           2
Tyler Zeller         2
                    ..
Jeremy Lamb          1
Amile Jefferson      1
Jared Dudley         1
Kalin Lucas          1
D'Angelo Russell     1
Theo Pinson          1
Dante Exum           1
Shaun Livingston     1
Ante Zizic           1
Scott Machado        1
Deng Adel            1
PJ Dozier            1
Dwayne Bacon         1
Bam Adebayo          1
Jose Calderon        1
Harry Giles III      1
E'Twaun Moore        1
Jarred Vanderbilt    1
James Harden         1
Gary Trent Jr.       1
Eric Bledsoe         1
Jemerrio Jones       1
Jarell Martin        1
Tony Parker          1
Jake Layman          1
Nicolas Batum        1
Jaylen Adams         1
Jodie Meeks          1
Sterling Brown       1
Cory Joseph          1
Name: DISPLAY_FIRST_LAST, Length: 530, dtype: int64

## 7:

Find the player who scored the least amount of points while playing in at least 40 games last season.

In [286]:

dfpts = df.groupby('DISPLAY_FIRST_LAST').PTS.sum().reset_index(name='total pts').sort_values(by='total pts', ascending=False)
dfpts.columns = ['index', 'pts']
df1 = df.DISPLAY_FIRST_LAST.value_counts().reset_index(name='games')
df1.merge(dfpts)[df1.games>=40].sort_values(by='pts').reset_index(drop=True).iloc[0]

index    Sindarius Thornwell
games                     64
pts                       62
Name: 0, dtype: object

# Part 4: Pandas and Probability

## 8: 

What is the probability that a random player had a game where they scored more than 40 points?

In [292]:
#your code here
sum(df['PTS']>40)/len(df['PTS'])

0.004214397915788667

## 9:

What is the probability that a randomly selected player from last season would average more than 20 points per game?

In [295]:
sum(df.groupby('DISPLAY_FIRST_LAST').PTS.mean()>20)/len(df.groupby('DISPLAY_FIRST_LAST'))

0.062264150943396226

# Advanced Questions

## 10: 
Find the player who scored the least amount of points while playing in at least 40 games and averageing at least 15 minutes per game last season.

In [ ]:
#your code here

## 11: 
Which player scored the largest share of points for their team throughout the season.

In [333]:
#your code here
df2 = df.groupby(['TEAM_ABBREVIATION', 'DISPLAY_FIRST_LAST']).PTS.sum().reset_index(name='pts_team')
df3 = df2.groupby('TEAM_ABBREVIATION').pts_team.sum().reset_index(name='team_pts')
df4 = df2.merge(df3)
df4['shared'] = df4['pts_team']/df4.team_pts
df5 = df4.groupby('TEAM_ABBREVIATION').shared.max().reset_index(name='percentage')
df4[df4['shared']==df4['shared'].max()]

    TEAM_ABBREVIATION DISPLAY_FIRST_LAST  pts_team  team_pts    shared
213               HOU       James Harden      2818      9341  0.301681

## 12:

What is the probability that a randomly selected player had at least one game in which they scored 40 points last season.

In [ ]:
# your code here

## 13: 

A double-double is when a player records for any of the two follow categories: points, rebounds, assists, steals, or blocks. 
What is the probability that a randomly selected player had a double-double in a game last season?

In [ ]:
#your code here

## 14:

What is the probability that a randomnly selected game had a player record a triple-double in that game?

In [ ]:
#your code here

# Part 5: Super Duper Challenge

## 15:

How many players last season averaged more points per game than their career average?